version: '2'
services:
 db:
  container_name: mysql-ld
  image: mysql:8.0
  command: --default-authentication-plugin=mysql_native_password
  volumes:
   - ldoc_db:/var/lib/mysql
  ports:
   - 3306:3306
  environment:
   - MYSQL_ROOT_PASSWORD=mysqlroot
   - MYSQL_DATABASE=logicaldoc
   - MYSQL_USER=ldoc
   - MYSQL_PASSWORD=changeme

 logicaldoc:     
  container_name: logicaldoc-ce
  image: logicaldoc/logicaldoc-ce
  depends_on:
   - db
  command: ["./wait-for-it.sh", "mysql-ld:3306", "-t", "30", "--", "/opt/logicaldoc/start-logicaldoc.sh", "run"]
  ports:
   - 8080:8080
  environment:
   - LDOC_MEMORY=2000
   - DB_HOST=mysql-ld
   - DB_NAME=logicaldoc
   - DB_USER=ldoc
   - DB_PASSWORD=changeme
  volumes:
   - ldoc_conf:/opt/logicaldoc/conf
   - ldoc_repository:/opt/logicaldoc/repository
#  ulimits:
#    nproc: 65535
#    nofile:
#      soft: 6000
#      hard: 40000
#  mem_limit: 7000000000

volumes:
  ldoc_db:
  ldoc_conf:
  ldoc_repository:


